### ISSUE TITLE
Can't run project: undeclared tsc dependency

### ISSUE THREAD

**Issue by asymmetric** [emostov/staking-payouts#22]
The README lists these steps:

```
git clone https://github.com/emostov/staking-payouts.git
cd staking-payouts
yarn run install
yarn run build
```

But both `yarn` commands fail.

```
$ yarn run install
yarn run v1.22.10
error Command "install" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```
$ yarn run build
yarn run v1.22.10
$ tsc -p tsconfig.json
/bin/sh: tsc: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```
$ yarn --version
1.22.10
```

**Comment by asymmetric** [comment]
Oh, I only now noticed `./node_modules/.bin/tsc` being already present. It wasn't in my `PATH` though.

Let me know if this is the expectation, and I'll close this issue and #23.

**Comment by emostov** [comment]
> Oh, I only now noticed ./node_modules/.bin/tsc being already present. It wasn't in my PATH though.

I am not actually sure, but I prefer your suggestion of adding the `typescript` dep explicitly instead of relying on it another dep to require it.
