### ISSUE TITLE
error: Unable to match provided value to a secret URI

### ISSUE THREAD

**Issue by SerafV1** [emostov/staking-payouts#4]
2021-03-16 19:18:50 [payouts] info: Sending tx: 
{
  "args": [
    "GvSbw75mBMQW6rNsVE6KL2NrnN9Vjkej4EKToe1Dya9vGgM",
    "2,013"
  ],
  "method": "payoutStakers",
  "section": "staking"
}
2021-03-16 19:18:50 [payouts] error: Unable to match provided value to a secret URI
2021-03-16 19:18:50 [payouts] info: Exiting ...

**Comment by emostov** [comment]
It looks the error is coming from polkadot-js keyring. See: https://github.com/polkadot-js/common/blob/c46cd5030ee5e5373af8fa7c1e111e25b38fdfd3/packages/util-crypto/src/key/extractSuri.ts#L21-L35

It looks like you are entering a invalid SURI. I would double check you are specifying the correct file path to the file that has your SURI. You should use the absolute path to the file and the debug log messages will print out the file path. 

If you are 100% sure you have the correct file path I would then check file itself and the SURI.

**Comment by SerafV1** [comment]
My fault, problem was in wrong phrase, script works fine.
